name: Create a release
on:
  push:
    tags:
      - 'release-v*'
jobs:
  prepare-release:
    name: Prepare release assets
    runs-on: ubuntu-latest
    env:
      SOURCE_TAG: ${{ github.ref }}
      IMAGE_NAMESPACE: jannfis
    steps:
      - name: Check if the published tag is well formed and setup vars
        run: |
          set -ue
          # Target version must match major.minor.patch and optional -rcX suffix
          # where X must be a number.
          TARGET_VERSION=${SOURCE_TAG#*release-v}
          if ! echo ${TARGET_VERSION} | egrep '^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)*$'; then
            echo "Target version '${TARGET_VERSION}' is malformed, refusing to continue." >&2
            exit 1
          fi

          # Target branch is the release branch we're going to operate on
          # Its name is 'release-<major>.<minor>'
          TARGET_BRANCH="release-${TARGET_VERSION%\.[0-9]*}"

          # The release tag is
          RELEASE_TAG="${SOURCE_TAG#*release-}"

          # Whether this is a pre-release (indicated by -rc suffix)
          PRE_RELEASE=false
          if echo "${RELEASE_TAG}" | egrep -- '-rc[0-9]+$'; then
            PRE_RELEASE=true
          fi

          # Make the variables available in follow-up steps
          echo "::set-env name=TARGET_VERSION::${TARGET_VERSION}"
          echo "::set-env name=TARGET_BRANCH::${TARGET_BRANCH}"
          echo "::set-env name=RELEASE_TAG::${RELEASE_TAG}"
          echo "::set-env name=PRE_RELEASE::${PRE_RELEASE}"
      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: '1.14.2'
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Setup Git author information
        run: |
          set -ue
          git config --global user.email "jann@mistrust.net"
          git config --global user.name "jannfis"
      - name: Checkout corresponding release branch
        run: |
          set -ue
          echo "Switching to release branch '${TARGET_BRANCH}'"
          git checkout ${TARGET_BRANCH}
      - name: Create VERSION information
        run: |
          set -ue
          echo "Bumping version from $(cat VERSION) to ${TARGET_VERSION}"
          echo "${TARGET_VERSION}" > VERSION
          git commit -m "Bump version to ${TARGET_VERSION}" VERSION
      - name: Generate new set of manifests
        run: |
          set -ue
          make install-codegen-tools-local
          helm2 init --client-only
          make manifests-local VERSION=${TARGET_VERSION}
          git diff
          git commit manifests/ -m "Bump version to ${TARGET_VERSION}"
      - name: Create release tag
        run: |
          set -ue
          echo "Creating release ${RELEASE_TAG}"
          git tag ${RELEASE_TAG}
      - name: Build Docker image for release
        run: |
          set -ue
          git clean -fd
          mkdir -p dist/
          make image IMAGE_TAG="${TARGET_VERSION}" DOCKER_PUSH=false
          make release-cli
          chmod +x ./dist/argocd-linux-amd64
          ./dist/argocd-linux-amd64 version --client
      - name: Push changes to release branch
        run: |
          git push origin ${TARGET_BRANCH}
          git push origin ${RELEASE_TAG}
      - name: Create GitHub release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_TAG }}
          draft: false
          pre_release: ${{ env.PRE_RELEASE }}
          body: |
            This is a test release. Yay.
      - name: Upload argocd-linux-amd64 binary to release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/argocd-linux-amd64
          asset_name: argocd-linux-amd64
          asset_content_type: application/octet-stream
      - name: Upload argocd-darwin-amd64 binary to release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/argocd-darwin-amd64
          asset_name: argocd-darwin-amd64
          asset_content_type: application/octet-stream
      - name: Upload argocd-windows-amd64 binary to release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/argocd-windows-amd64.exe
          asset_name: argocd-windows-amd64.exe
          asset_content_type: application/octet-stream