name: Create a release
on:
  push:
    tags:
      - 'release-v*'
jobs:
  prepare-release:
    name: Prepare release assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create release tag
        env:
          SOURCE_TAG: ${{ github.ref }}
        run: |
          #!/bin/bash
          RELEASE_TAG=${SOURCE_TAG:18}
          echo "Creating release ${RELEASE_TAG}"
          git tag -a -m "Release ${RELEASE_TAG}" ${RELEASE_TAG}
          git push --tags
