name: Create a release
on:
  push:
    tags:
      - 'release-v*'
jobs:
  prepare-release:
    name: Prepare release assets
    runs-on: ubuntu-latest
    env:
      SOURCE_TAG: ${{ github.ref }}
    steps:
      - name: Check if the published tag is well formed
        run: |
          TARGET_VERSION=${SOURCE_TAG#*v}
          if ! echo ${TARGET_VERSION} | egrep '^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)*$'; then
            echo "Target version '${TARGET_VERSION}' is malformed, refusing to continue."
            exit 1
          fi
          TARGET_BRANCH="release-${TARGET_VERSION%\.[0-9]*}"
          RELEASE_TAG="${SOURCE_TAG:#release-}"

          echo "TARGET_VERSION=${TARGET_VERSION}" > ~/release-vars.sh
          echo "TARGET_BRANCH=${TARGET_BRANCH}" >> ~/release-vars.sh
          echo "RELEASE_TAG=${RELEASE_TAG}" >> ~/release-vars.sh
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Setup Git author information
        run: |
          git config --global user.email "jann@mistrust.net"
          git config --global user.name "jannfis"
      - name: Checkout corresponding release branch
        run: |
          #TARGET_VERSION=${SOURCE_TAG#*v}
          #TARGET_BRANCH="release-${TARGET_VERSION%\.[0-9]*}"
          . ~/release-vars.sh
          echo "Switching to release branch '${TARGET_BRANCH}'"
          git checkout ${TARGET_BRANCH}
      - name: Create VERSION information
        run: |
          . ~/release-vars.sh
          #TARGET_VERSION=${SOURCE_TAG#*v}
          echo "Bumping version from $(cat VERSION) to ${TARGET_VERSION}"
          echo "${TARGET_VERSION}" > VERSION
          git commit -m "Bump version to ${TARGET_VERSION}" VERSION
          git push
      - name: Create release tag
        run: |
          #!/bin/bash
          #RELEASE_TAG=${SOURCE_TAG:18}
          . ~/release-vars.sh
          echo "Creating release ${RELEASE_TAG}"
          git tag -a -m "Release ${RELEASE_TAG}" ${RELEASE_TAG}
          git push origin ${RELEASE_TAG}
